name: CI for OBS Service Cargo

on:
  push:
    paths:
      - '**.rs'
      - '**/github/**.yaml'
      - '**/github/**.yml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '!**.md'
  pull_request:
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '!**.md'

env:
  CARGO_TERM_COLOR: always
  TOOLCHAIN_VERSION: stable

jobs:
  build:
    runs-on: ubuntu-latest
    container: opensuse/leap
    steps:
    - name: Install tar, gzip, dependencies and Rust
      run: |
        zypper --non-interactive -vvv in tar gzip libzstd-devel rustup openssl-devel
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        cargo update
        cargo build --release --all-features
  
  style:
    runs-on: ubuntu-latest
    container: opensuse/leap
    steps:
    - name: Install tar, gzip, dependencies and Rust
      run: |
        zypper --non-interactive -vvv in tar gzip libzstd-devel rustup openssl-devel
    - name: Checkout
      uses: actions/checkout@v4
    - name: Check formatting
      run: |
        cargo fmt -- --check || true
    - name: Check clippy
      run: |
        cargo clippy
        cargo clippy --tests
  
  tests:
    runs-on: ubuntu-latest
    container: opensuse/leap
    steps:
    - name: Install tar, gzip, dependencies and Rust
      run: |
        zypper --non-interactive -vvv in tar gzip libzstd-devel rustup openssl-devel
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install cargo-vendor-filterer
      run: |
        cargo install cargo-vendor-filterer
    - name: Run sample projects to test
      run: |
        export PATH="${PATH}:${HOME}/.cargo/bin"
        echo "${PATH}"
        cargo test --release -- --test-threads=1
        cargo test --release -- --test-threads=1 --ignored
